config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :slides do
      collection do
        post :update_positions
      end
    end
  end
  namespace :admin do
    resource :showcase_settings
  end
end

app/models/spree/slide.rb
module Spree
  class Slide < ActiveRecord::Base

    has_attached_file :image,
      :styles=>{:thumb=> ["#{SpreeShowcase::Config.thumbnail_style}"],
                :showcase=> ["#{SpreeShowcase::Config.showcase_style}"]},
      :url => '/spree/showcase/:id/:style/:basename.:extension',
      :path => ':rails_root/public/spree/showcase/:id/:style/:basename.:extension'
    
    # Add S3 and Heroku support
    s3_options = if ENV['S3_KEY'] && ENV['S3_SECRET'] && ENV['S3_BUCKET']
      {
        :storage => 's3',
        :s3_credentials => {
          :access_key_id     => ENV['S3_KEY'],
          :secret_access_key => ENV['S3_SECRET']
        },
        :bucket => ENV['S3_BUCKET']
      }
    elsif (s3_config_file = Rails.root.join('config','s3.yml')).exist?
      {
        :storage => 's3',
        :s3_credentials => s3_config_file
      }
    else
      { :storage => 'filesystem' }
    end

    attachment_definitions[:image] = (attachment_definitions[:image] || {}).merge(s3_options)
    
    default_scope order(:position) # Slides should always be ordered by position specified by user.
    scope :published, where(:published=>true)
    scope :no_slides, lambda {|num| limit(num)}
    attr_accessible :name, :body, :target_url, :published, :image, :thumbnail_message
  end
end

app/controllers/spree/admin/showcase_settings_controller.rb
module Spree
  module Admin
    class ShowcaseSettingsController < BaseController
     def show
        @preferences = [:enabled,
                        :thumbnail_style,
                        :showcase_style,
                        :number_of_slides_to_show,
                        :slideshow,
                        :animation_type,
                        :slideshow_speed,
                        :animation_duration,
                        :randomize,
                        :animation_loop,
                        :pause_on_hover]
      end
     
      def edit
        @preferences = [:enabled,
                        :thumbnail_style,
                        :showcase_style,
                        :number_of_slides_to_show,
                        :slideshow,
                        :animation_type,
                        :slideshow_speed,
                        :animation_duration,
                        :randomize,
                        :animation_loop,
                        :pause_on_hover]
      end
     
      def update
        params.each do |name, value|
          next unless SpreeShowcase::Config.has_preference? name
          SpreeShowcase::Config[name] = value
        end
     
        redirect_to admin_showcase_settings_path
      end
    end
  end
end

app/controllers/spree/admin/slides_controller.rb
module Spree
  module Admin
    class SlidesController < ResourceController
      respond_to :html
      
      # Copied over from the Spree Core. 
      def update_positions
        params[:positions].each do |id, index|
          Slide.where(:id => id).update_all(:position => index)
        end

        respond_to do |format|
          format.js  { render :text => 'Ok' }
        end
      end 

      def index
        @slides = Slide.all # There is a default_scope order(:position) in effect.
      end
      
     
  
    end
  end
end

app/views/spree/admin/shared/_showcase_settings.html.erb
<div>
	<p>Please remember to run rake after changing picture styles</p>
	<pre>rake paperclip:refresh class=Spree::Slide</pre>
</div>

app/views/spree/admin/shared/_showcase_submenu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav" data-hook="admin_showcase_sub_tabs">
    <%= tab :slides, :match_path => '/slides' %>
    <%= tab :showcase_settings, :match_path => '/showcase_settings' %>
  </ul>
<% end %>

app/views/spree/admin/showcase_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>
<%= render :partial=>'spree/admin/shared/showcase_submenu'%>
<h1><%= t(:edit_showcase_settings) %></h1>

<%= form_tag admin_showcase_settings_path, :method => :put do %>
  <fieldset id="preferences" data-hook>
  <% @preferences.each do |key| 
      type = SpreeShowcase::Config.preference_type(key) %>
      <%= label_tag(key, t(key) + ': ') + tag(:br) if type != :boolean %>
      <%= preference_field_tag(key, SpreeShowcase::Config[key], :type => type) %>
      <%= label_tag(key, t(key)) + tag(:br) if type == :boolean %> <br />
  <% end %>
  </fieldset>
  <p class="form-buttons" data-hook="buttons">
    <%= button t(:update) %>
    <%= t(:or) %> <%= link_to t(:cancel), admin_showcase_settings_url %>
  </p>
<% end %>
	<%= render :partial =>"spree/admin/shared/showcase_settings" %>

app/views/spree/admin/showcase_settings/show.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>
<%= render :partial=>'spree/admin/shared/showcase_submenu'%>
<h1><%= t(:showcase_settings) %></h1>

<table data-hook="preferences">
  <% @preferences.each do |key| %>
  <tr>
    <th scope="row"><%= t(key) %>:</th>
    <td><%= SpreeShowcase::Config[key] %></td>
  </tr>
  <% end %> 
</table>

<p><%= link_to_with_icon 'edit', t(:edit), edit_admin_showcase_settings_path, :id => 'admin_showcase_settings_link' %></p>

	<%= render :partial =>"spree/admin/shared/showcase_settings" %>

app/views/spree/admin/slides/_form.html.erb
<%= f.field_container :name do %>
  <%= f.label :name, t(:name) %><br />
  <%= f.text_field :name %>
<% end %>
<%= f.field_container :body do %>
  <%= f.label :body, t(:body) %><br />
  <%= f.text_area :body, {:cols => 60, :rows => 4, :class => 'fullwidth', :id=>:page_body} %>
<% end %>

<%= f.field_container :target_url do %>
  <%= f.label :target_url, t(:target_url) %><br />
  <%= f.text_field :target_url %>
<% end %>

<%= f.field_container :image do %>
  <%= f.label :image, t(:image) %><br />
  <%= f.file_field :image %>
<% end %>

<%= f.field_container :thumbnail_message do %>
	<%= f.label :thumbnail_message, t(:thumbnail_message) %>
	<%= f.text_field :thumbnail_message %>
<% end %>
<%= f.field_container :published do %>
  <%= f.label :is_published, t(:published) %><br />
  <%= f.check_box :published %>
<% end %>

app/views/spree/admin/slides/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>
<%= render :partial=>'spree/admin/shared/showcase_submenu'%>
<h1>Editing Slide</h1>

<%= render 'spree/shared/error_messages', :target => @slide %>

<%= form_for [:admin, @slide], :html => { :multipart => true } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/slides/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>
<%= render :partial=>'spree/admin/shared/showcase_submenu'%>
<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li>
      <p><%= button_link_to t(:new_slide), new_object_url, :icon => 'add', :id => 'admin_new_slide_link' %></p>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t(:showcase) %></h1>

<table class="index sortable" id="listing_slides" data-hook data-sortable-link="<%= update_positions_admin_slides_url %>">
  <thead>
    <tr data-hook="admin_slides_index_headers">
      <th><%= t(:name) %></th>
      <th data-hook="admin_slides_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @slides.each do |slide|%>
      <tr id="<%= spree_dom_id slide %>" data-hook="admin_slides_index_rows">
        <td width="350px" ><span class="handle" style="margin-right:5px"> </span> <%=link_to slide.name, object_url(slide) %></td>
        <td data-hook="admin_slides_index_row_actions">
          <%= link_to_edit slide, :class => 'edit' %> &nbsp;
          <%= link_to_delete slide %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/slides/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>
<%= render :partial=>'spree/admin/shared/showcase_submenu'%>
<h1><%= t(:new_showcase_slide) %></h1>
<%= render 'spree/shared/error_messages', :target => @slide %>

<%= form_for [:admin, @slide] , :html => { :multipart => true } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p class="form-buttons" data-hook="buttons"><%= button t(:create) %></p>
<% end %>

app/views/spree/admin/slides/show.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>
<%= render :partial=>'spree/admin/shared/showcase_submenu'%>
<h1><%= t(:slide) %></h1>

<table>
  <tr data-hook="name">
    <th><%= t(:name) %></th>
    <td>
      <%= @slide.name %>
    </td>
  </tr>
  <tr data-hook="body">
    <th><%= t(:body) %></th>
    <td>
      <%= @slide.body %>
    </td>
  </tr>
  <tr data-hook="link_url">
    <th><%= t(:target_url) %></th>
    <td>
      <%= @slide.target_url %>
    </td>
  </tr>
  <tr data-hook="published">
    <th><%= t(:published) %></th>
    <td>
      <%= @slide.published %>
    </td>
  </tr>
  <tr data-hook="image_file_name">
    <th><%= t(:image) %></th>
    <td>
      <%= @slide.image_file_name %>
    </td>
  </tr>
</table>

<p>
  <%= link_to_edit @slide, :class => 'edit_slide' %> <%= t(:or) %>
  <%= link_to t(:back), collection_url %>
</p>

app/views/spree/slides/_content_insert.html.erb
<% if SpreeShowcase::Config.enabled %>
	<% content_for :spree_showcase do %>
		  <%= render :partial => 'spree/slides/showcase' %>
	<% end %>
<% end %>

app/views/spree/slides/_showcase.html.erb
<div class="flex-container">
	<div class="row">
		<div class="flexslider alpha omega sixteen columns">
		  <ul class="slides">
				<% Spree::Slide.published.no_slides(SpreeShowcase::Config.number_of_slides_to_show).each do |slide| %>
					<li>
						<%= link_to(slide.target_url.present? ? slide.target_url : "#") do %>
							<%= slide.image.present? ? image_tag(slide.image.url(:showcase)) : image_tag("http://www.placehold.it/#{SpreeShowcase::Config.preferences[:showcase_style].match(/\d{2,}x\d{2,}/)}&text=Spree%20Showcase%20by%20@daemonsy") %>
						<% end %>
					</li>
				<% end %>
		  </ul>
		</div>
	</div>
</div>
<%= javascript_tag do %>
  $(window).load(function() {
    $('.flexslider').flexslider({
      animation:         "<%= SpreeShowcase::Config[:animation_type] %>",     // String: Select your animation type, "fade" or "slide"
      slideDirection:    "horizontal",                                        // String: Select the sliding direction, "horizontal" or "vertical"
      slideshow:         '<%= SpreeShowcase::Config[:slideshow] %>',          // Boolean: Animate slider automatically
      slideshowSpeed:    '<%= SpreeShowcase::Config[:slideshow_speed] %>',    // Integer: Set the speed of the slideshow cycling, in milliseconds
      animationDuration: '<%= SpreeShowcase::Config[:animation_duration] %>', // Integer: Set the speed of animations, in milliseconds
      directionNav:      false,                                               // Boolean: Create navigation for previous/next navigation? (true/false)
      controlNav:        true,                                                // Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
      keyboardNav:       true,                                                // Boolean: Allow slider navigating via keyboard left/right keys
      mousewheel:        false,                                               // Boolean: Allow slider navigating via mousewheel
      prevText:          "Previous",                                          // String: Set the text for the "previous" directionNav item
      nextText:          "Next",                                              // String: Set the text for the "next" directionNav item
      pausePlay:         false,                                               // Boolean: Create pause/play dynamic element
      pauseText:         'Pause',                                             // String: Set the text for the "pause" pausePlay item
      playText:          'Play',                                              // String: Set the text for the "play" pausePlay item
      randomize:         '<%= SpreeShowcase::Config[:randomize] %>',          // Boolean: Randomize slide order
      slideToStart:      0,                                                   // Integer: The slide that the slider should start on. Array notation (0 = first slide)
      animationLoop:     '<%= SpreeShowcase::Config[:animation_loop] %>',     // Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
      pauseOnAction:     true,                                                // Boolean: Pause the slideshow when interacting with control elements, highly recommended.
      pauseOnHover:      '<%= SpreeShowcase::Config[:pause_on_hover] %>',     // Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
      controlsContainer: '.flex-container',                                   // Selector: Declare which container the navigation elements should be appended too. Default container is the flexSlider element. Example use would be ".flexslider-container", "#container", etc. If the given element is not found, the default action will be taken.
      manualControls:    '.custom-controls li a',                             // Selector: Declare custom control navigation. Example would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
      start:             function(){},                                        // Callback: function(slider) - Fires when the slider loads the first slide
      before:            function(){},                                        // Callback: function(slider) - Fires asynchronously with each slider animation
      after:             function(){},                                        // Callback: function(slider) - Fires after each slider animation completes
      end:               function(){}                                         // Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
    });
  });
<% end %>